version: '3.9'

services:
  php:
    build:
      context: ../
      dockerfile: .docker/php.Dockerfile
    image: ${NAME}-php:${TAG}
    container_name: ${NAME}-php
    restart: always
    volumes:
      - ../:/workdir
      - php-sock:/var/run/php-fpm
      - postgres-sock:/var/run/postgresql
      - ./php/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./php/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/usr/local/etc/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    depends_on:
      - postgres
    expose:
      - 9000

  phpnginx:
    build:
      context: ../
      dockerfile: .docker/phpnginx.Dockerfile
    image: ${NAME}-phpnginx:${TAG}
    container_name: ${NAME}-phpnginx
    restart: always
    volumes:
      - ../:/workdir
      - php-sock:/var/run/php-fpm
      - ./php/etc/nginx/conf:/etc/nginx/conf
      - ./php/etc/nginx/templates:/etc/nginx/templates
      - ./php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    expose:
      - 80
      - 443
    ports:
      - 7001:81
      - 7002:82

  postgres:
    build:
      context: ../
      dockerfile: .docker/postgres.Dockerfile
    image: ${NAME}-postgres:${TAG}
    container_name: ${NAME}-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: c0b4d1b4c4
    command: postgres -c config_file=/usr/share/postgresql/postgresql.conf
    volumes:
      - ../:/workdir
      - postgres-sock:/var/run/postgresql
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/usr/share/postgresql/postgresql.conf:/usr/share/postgresql/postgresql.conf
    expose:
      - 5432
    ports:
      - 5432:5432

  pgadmin:
    build:
      context: ../
      dockerfile: .docker/pgadmin.Dockerfile
    image: ${NAME}-pgadmin:${TAG}
    container_name: ${NAME}-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.com
      PGADMIN_DEFAULT_PASSWORD: c0b4d1b4c4
    volumes:
      - ../storage/pgadmin:/var/lib/pgadmin/storage
    expose:
      - 5432
    ports:
      - 5050:80

volumes:
  php-sock:
    name: ${NAME}-php-sock
    driver: local
  postgres-sock:
    name: ${NAME}-postgres-sock
    driver: local
  postgres-data:
    name: ${NAME}-postgres-data
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: ${SCRIPT_CURRENT_DIR}/postgres/var/lib/postgresql/data

networks:
  default:
    name: ${NAME}
    driver: bridge